[package]
name = "trunk"
version = "0.9.2"
edition = "2018"
description = "Build, bundle & ship your Rust WASM application to the web."
license = "MIT/Apache-2.0"
authors = ["Anthony Dodd <dodd.anthonyjosiah@gmail.com>"]
repository = "https://github.com/thedodd/trunk"
readme = "README.md"
categories = ["command-line-utilities", "wasm", "web-programming"]
keywords = ["wasm", "bundler", "web", "build-tool", "compiler"]

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"

[dependencies]
anyhow = "1"
async-process = "1"
async-std = { version = "1.9", default-features = false, features = ["attributes", "std", "unstable"] }
async-tungstenite = { version = "0.10.0", default-features = false, features = ["async-std-runtime"] }
atty = "0.2.14"
cargo_metadata = "0.12"
crossbeam-channel = "0.5"
console = "0.14"
dunce = "1"
envy = "0.4"
fs_extra = "1"
futures = "0.3"
http-types = "2"
indicatif = "0.15"
nipper = { version = "0.1.9", package = "nipper-trunk" }
notify = "4"
open = "1"
remove_dir_all = "0.6"
sass-rs = "0.2.2"
seahash = "4"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
structopt = "0.3"
structopt-derive = "0.4"
surf = "2"
tide = { version = "0.16.0", features = ["unstable"] }
tide-websockets = "0.3.0"
toml = "0.5"

[dev-dependencies]
insta = "0.16.1"
